version: 2.1

orbs:
  node: circleci/node@5.0.2
  
jobs:
  test:
    docker:
      - image: cimg/node:19.3.0
    steps:
      - checkout
      - run: node --version

workflows:
  test-deploy:
    jobs:
      -test
